// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bfoaumuyvrzkleveselu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmb2F1bXV5dnJ6a2xldmVzZWx1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NDIxOTAsImV4cCI6MjA3MDQxODE5MH0.mT44L2BulismESklkOmcyZ7lr5rtl7F_qtlDfGSTLWY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});